// Auto-generated by theme-switcher - do not edit manually
pragma Singleton
import QtQuick

QtObject {
    // Base colors
    readonly property color background: "{background}"
    readonly property color backgroundLight: "{background_light}"
    readonly property color foreground: "{foreground}"
    readonly property color foregroundDim: "{foreground_dim}"

    // Accent colors
    readonly property color accent: "{accent}"
    readonly property color accentBright: "{accent_bright}"

    // Semantic colors
    readonly property color red: "{red}"
    readonly property color green: "{green}"
    readonly property color yellow: "{yellow}"
    readonly property color blue: "{blue}"
    readonly property color magenta: "{magenta}"
    readonly property color cyan: "{cyan}"

    // Bright variants
    readonly property color redBright: "{red_bright}"
    readonly property color greenBright: "{green_bright}"
    readonly property color yellowBright: "{yellow_bright}"
    readonly property color blueBright: "{blue_bright}"
    readonly property color magentaBright: "{magenta_bright}"
    readonly property color cyanBright: "{cyan_bright}"

    // UI specific
    readonly property color separator: "{separator}"
    readonly property color workspaceActive: "{workspace_active}"
    readonly property color workspaceOccupied: "{workspace_occupied}"
    readonly property color workspaceEmpty: "{workspace_empty}"

    // Font
    readonly property string fontFamily: "{font_family}"
}
